import Head from "next/head";

export default function Layout({
	children,
}) {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<nav class="bg-gray-800">
				<div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
					<div class="relative flex items-center justify-between h-16">
						<div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
							<button
								type="button"
								class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
								aria-controls="mobile-menu"
								aria-expanded="false"
							>
								<span class="sr-only">
									Open main menu
								</span>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									class=" text-red-400 h-9 w-9"
									fill="none"
									viewBox="0 0 24 24"
									stroke="currentColor"
								>
									<path
										stroke-linecap="round"
										stroke-linejoin="round"
										stroke-width="2"
										d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"
									/>
								</svg>{" "}
								<svg
									class="hidden h-6 w-6"
									xmlns="http://www.w3.org/2000/svg"
									fill="none"
									viewBox="0 0 24 24"
									stroke="currentColor"
									aria-hidden="true"
								>
									<path
										stroke-linecap="round"
										stroke-linejoin="round"
										stroke-width="2"
										d="M6 18L18 6M6 6l12 12"
									/>
								</svg>
							</button>
						</div>
						<div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
							<div class="flex-shrink-0 flex items-center">
								<a
									type="button"
									class="bg-gray-800 flex text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
									id="user-menu-button"
									aria-expanded="false"
									aria-haspopup="true"
									href="https://www.armyacademy.ro/"
									target="_black"
								>
									<span class="sr-only">
										Open user menu
									</span>
									<img
										class="h-10 w-10 rounded-full"
										src="\images\logo.png"
										alt=""
									></img>
								</a>
							</div>
							<div class="hidden sm:block sm:ml-6">
								<div class="flex space-x-4">
									<a
										href="/"
										class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium"
										aria-current="page"
									>
										Studenti
									</a>
									<a
										href="/admin"
										class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
									>
										Admin Menu1
									</a>
									<a
										href="/admin2"
										class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
									>
										Admin Menu2
									</a>
									<a
										href="/regulament"
										class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
									>
										Regulament
									</a>
								</div>
							</div>
						</div>
						<div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
							<div class="ml-3 relative">
								<div>
									<button
										type="button"
										class="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
										id="user-menu-button"
										aria-expanded="false"
										aria-haspopup="true"
									>
										<span class="sr-only">
											Open user menu
										</span>
									</button>
								</div>
							</div>

							<div class="relative">
								<a
									href="/calculator"
									class="text-gray-300 hover:bg-gray-500 hover:text-white px-3 py-2 rounded-md text-md font-medium"
								>
									Login
								</a>
							</div>
						</div>
					</div>
				</div>

				<div
					class="sm:hidden"
					id="mobile-menu"
				>
					<div class="px-2 pt-2 pb-3 space-y-1">
						<a
							href="/"
							class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium"
							aria-current="page"
						>
							Studenti
						</a>

						<a
							href="/admin"
							class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
						>
							Admin Menu1
						</a>
						<a
							href="/admin2"
							class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
						>
							Admin Menu2
						</a>
						<a
							href="/regulament"
							class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
						>
							Regulament
						</a>
					</div>
				</div>
			</nav>
			{children}
		</div>
	);
}
