import Head from "next/head";
import Layout from "../components/layout";
import { useRef } from "react";
import useSWR from "swr";


async function createPost(
  enteredid,
  enterednume,
  enteredprenume,
  enteredpluton,
  enteredcompanie,
  enteredbatalion,
  enterednrtelefon,
  enteredistoric,
  enteredpuncte
) {
	const response = await fetch("/api/add", {
		method: "POST",
		body: JSON.stringify({
			enteredid,
			enterednume,
			enteredprenume,
			enteredpluton,
			enteredcompanie,
			enteredbatalion,
			enterednrtelefon,
			enteredistoric,
			enteredpuncte
		}),
		headers: {
			"Content-Type": "application/json",
		},
	});

	const data = await response.json();

	if (!response.ok) {
		throw new Error(data.message || "Something went wrong!");
	}

	return data;
}



export default function AddSd() {
	const inputid = useRef();
	const inputnume = useRef();
	const inputprenume = useRef();
	const inputpluton = useRef();
	const inputcompanie = useRef();
	const inputbatalion = useRef();
	const inputnrtelefon = useRef();
	const inputistoric = useRef();
	const inputpuncte = useRef();

	async function submitHandler(event) {
		event.preventDefault();
		alert("Student adaugat cu succes");
		const enteredid = inputid.current.value;
		const enterednume = inputnume.current.value;
		const enteredprenume = inputprenume.current.value;
		const enteredpluton = inputpluton.current.value;
		const enteredcompanie = inputcompanie.current.value;
		const enteredbatalion = inputbatalion.current.value;
		const enterednrtelefon = inputnrtelefon.current.value;
		const enteredistoric = inputistoric.current.value;
		const enteredpuncte = inputpuncte.current.value;

		const result = await createPost(
			enteredid,
			enterednume,
			enteredprenume,
			enteredpluton,
			enteredcompanie,
			enteredbatalion,
			enterednrtelefon,
			enteredistoric,
			enteredpuncte
		);

	}

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div class="flex justify-center pt-5 px-3">
					<form onSubmit={submitHandler}  method="POST" class="w-full max-w-lg">
						<div class="flex flex-wrap -mx-3 mb-0">
							<div class="w-full px-3">
								<label
									class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
									for="grid-password"
								>
									Id/CNP{" "}
								</label>
								<input
									class="appearance-none block w-full bg-gray-200 border-red-500 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
									id="grid-id"
									type="text"
									placeholder="ID"
									ref={inputid}
								/>
								{/* <p class="text-gray-600 text-xs italic py-0.5">
									Make it as long and as
									crazy as you'd like
								</p> */}
							</div>
							<div class="w-1/2 px-3 mb-6 md:mb-0">
								<label
									class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
									for="grid-first-name"
								>
									Nume
								</label>
								<input
									class="appearance-none block w-full bg-gray-200 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
									id="nume"
									type="text"
									placeholder="Nume"
									ref={inputnume}
								/>
							</div>
							<div class="w-1/2 px-3">
								<label
									class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
									for="grid-last-name"
								>
									Prenume
								</label>
								<input
									class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
									id="preume"
									type="text"
									placeholder="Prenume"
									ref={inputprenume}
								/>
							</div>
						</div>

						<div class="flex flex-wrap -mx-3 mb-2">
							<div class="w-1/3 px-3 mb-6 md:mb-0">
								<label
									class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
									for="grid-state"
								>
									Pluton
								</label>
								<div class="relative">
									<select
										class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
										id="grid-state"
										ref={inputpluton}
									>
										<option>1</option>
										<option>2</option>
										<option>3</option>
										<option>4</option>
										<option>5</option>
									</select>
									<div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
										<svg
											class="fill-current h-4 w-4"
											xmlns="http://www.w3.org/2000/svg"
											viewBox="0 0 20 20"
										>
											<path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
										</svg>
									</div>
								</div>
							</div>
							<div class="w-1/3 px-3 mb-6 md:mb-0">
								<label
									class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
									for="grid-state"
								>
									Companie
								</label>
								<div class="relative">
									<select
										class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
										id="grid-state"
										ref={inputcompanie}
									>
										<option>1</option>
										<option>2</option>
										<option>3</option>
									</select>
									<div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
										<svg
											class="fill-current h-4 w-4"
											xmlns="http://www.w3.org/2000/svg"
											viewBox="0 0 20 20"
										>
											<path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
										</svg>
									</div>
								</div>
							</div>
							<div class="w-1/3 px-3 mb-6 md:mb-0">
								<label
									class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
									for="grid-state"
								>
									Batalion
								</label>
								<div class="relative">
									<select
										class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
										id="grid-state"
										ref={inputbatalion}
									>
										<option>1</option>
										<option>2</option>
										<option>3</option>
									</select>
									<div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
										<svg
											class="fill-current h-4 w-4"
											xmlns="http://www.w3.org/2000/svg"
											viewBox="0 0 20 20"
										>
											<path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
										</svg>
									</div>
								</div>
							</div>
						</div>
						<label
							class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
							for="grid-password"
						>
							Nr.Telefon{" "}
						</label>
						<input
							class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
							id="telefon"
							type="text"
							placeholder="07********"
							ref={inputnrtelefon}
						/>
						<label
							class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
							for="grid-password"
						>
							ISTORIC Disciplinar{" "}
						</label>
						<input
							class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
							id="grid-id"
							type="text"
							placeholder="Abateri / Recompense"
							ref={inputistoric}
						/>
						<label
							class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
							for="grid-password"
						>
							Puncte Acumulate{" "}
						</label>
						<input
							class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
							id="grid-id"
							type="text"
							placeholder="Puncte"
							ref={inputpuncte}
						/>

						<div class="pt-2 flex justify-center">
							<button class="shadow bg-red-500 hover:bg-red-600 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded">
								Adauga
							</button>
							<button
								type="reset"
								class=" mx-3 shadow bg-green-500 hover:bg-green-600 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded"
							>
								Reset
							</button>
						</div>
					</form>
				</div>
			</Layout>
		</div>
	);
}
