import Head from 'next/head';
import Layout from '../components/layout';
import { useState, useContext } from 'react';
import valid from '../utils/valid';
import { postData } from '../utils/fetchData';
import { DataContext } from '../store/GlobalState';

export default function AddSd() {
  const initialState = {
    Id: '',
    nume: '',
    prenume: '',
    pluton: '1',
    companie: '1',
    batalion: '1',
    telefon: '',
    istoric: 'Default : Nu Exista',
    puncte: ''
  };
  const [sdData, setSdData] = useState(initialState);

  const { Id, nume, prenume, pluton, companie, batalion, telefon, istoric, puncte } = sdData;
  const [state, dispatch] = useContext(DataContext);

  const handleChangeInput = (e) => {
    const { name, value } = e.target;
    setSdData({ ...sdData, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const errMsg = valid(Id, nume, prenume, pluton, companie, batalion, telefon, istoric, puncte);
    if (errMsg) {
      return dispatch({ type: 'NOTIFY', payload: { error: errMsg } });
    }
    dispatch({ type: 'NOTIFY', payload: { Loading: true } });

    const res = await postData('/add', sdData);
    if (errMsg) {
      return dispatch({ type: 'NOTIFY', payload: { error: res.err } });
    }      return dispatch({ type: 'NOTIFY', payload: { success: res.msg } });

    console.log(res);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div class="flex justify-center pt-5 px-3">
          <form onSubmit={handleSubmit} class="w-full max-w-lg">
            <div class="flex flex-wrap -mx-3 mb-0">
              <div class="w-full px-3">
                <label
                  class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                  for="grid-password">
                  Id/CNP{' '}
                </label>
                <input
                  class="appearance-none block w-full bg-gray-200 border-red-500 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                  id="grid-id"
                  type="text"
                  placeholder="ID"
                  name="Id"
                  value={Id}
                  onChange={handleChangeInput}
                />
                {/* <p class="text-gray-600 text-xs italic py-0.5">
									Make it as long and as
									crazy as you'd like
								</p> */}
              </div>
              <div class="w-1/2 px-3 mb-6 md:mb-0">
                <label
                  class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                  for="grid-first-name">
                  Nume
                </label>
                <input
                  class="appearance-none block w-full bg-gray-200 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                  id="nume"
                  type="text"
                  placeholder="Nume"
                  name="nume"
                  value={nume}
                  onChange={handleChangeInput}
                />
              </div>
              <div class="w-1/2 px-3">
                <label
                  class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                  for="grid-last-name">
                  Prenume
                </label>
                <input
                  class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                  id="preume"
                  type="text"
                  placeholder="Prenume"
                  name="prenume"
                  value={prenume}
                  onChange={handleChangeInput}
                />
              </div>
            </div>

            <div class="flex flex-wrap -mx-3 mb-2">
              <div class="w-1/3 px-3 mb-6 md:mb-0">
                <label
                  class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                  for="grid-state">
                  Pluton
                </label>
                <div class="relative">
                  <select
                    class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                    id="grid-state"
                    name="pluton"
                    value={pluton}
                    onChange={handleChangeInput}>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                  </select>
                  <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                    <svg
                      class="fill-current h-4 w-4"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 20 20">
                      <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                    </svg>
                  </div>
                </div>
              </div>
              <div class="w-1/3 px-3 mb-6 md:mb-0">
                <label
                  class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                  for="grid-state">
                  Companie
                </label>
                <div class="relative">
                  <select
                    class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                    id="grid-state"
                    name="companie"
                    value={companie}
                    onChange={handleChangeInput}>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                  </select>
                  <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                    <svg
                      class="fill-current h-4 w-4"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 20 20">
                      <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                    </svg>
                  </div>
                </div>
              </div>
              <div class="w-1/3 px-3 mb-6 md:mb-0">
                <label
                  class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                  for="grid-state">
                  Batalion
                </label>
                <div class="relative">
                  <select
                    class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                    id="grid-state"
                    name="batalion"
                    value={batalion}
                    onChange={handleChangeInput}>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                  </select>
                  <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                    <svg
                      class="fill-current h-4 w-4"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 20 20">
                      <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                    </svg>
                  </div>
                </div>
              </div>
            </div>
            <label
              class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
              for="grid-password">
              Nr.Telefon{' '}
            </label>
            <input
              class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
              id="telefon"
              type="text"
              placeholder="07********"
              name="telefon"
              value={telefon}
              onChange={handleChangeInput}
            />
            <label
              class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
              for="grid-password">
              ISTORIC Disciplinar{' '}
            </label>
            <input
              class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
              id="grid-id"
              type="text"
              placeholder="Abateri / Recompense"
              name="istoric"
              value={istoric}
              onChange={handleChangeInput}
            />
            <label
              class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
              for="grid-password">
              Puncte Acumulate{' '}
            </label>
            <input
              class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
              id="grid-id"
              type="text"
              placeholder="Puncte"
              name="puncte"
              value={puncte}
              onChange={handleChangeInput}
            />

            <div class="pt-2 flex justify-center">
              <button
                type="submit"
                class="shadow bg-red-500 hover:bg-red-600 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded">
                Adauga
              </button>
              <a
                href="/admin"
                type="reset"
                class=" mx-3 shadow bg-green-500 hover:bg-green-600 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded">
                Reset
              </a>
            </div>
          </form>
        </div>
      </Layout>
    </div>
  );
}
