import Head from "next/head";
import Layout from "../components/layout";
import { useRef } from "react";
import {
	useState,
	useEffect,
} from "react";

export default function Calculator() {
	const Rs1 = useRef();
	const Rs2 = useRef();
	const Rs3 = useRef();
	const Rs4 = useRef();
	const Rs5 = useRef();

	const Rp1 = useRef();
	const Rp2 = useRef();
	const Rp3 = useRef();
	const Rp4 = useRef();
	const Rp5 = useRef();

	function submitHandler(event) {
		event.preventDefault();
		const Rss1 = Rs1.current.value;
		const Rss2 = Rs2.current.value;
		const Rss3 = Rs3.current.value;
		const Rss4 = Rs4.current.value;
		const Rss5 = Rs5.current.value;
		const rezistente = [
			Rss1,
			Rss2,
			Rss3,
			Rss4,
			Rss5,
		];
		let j = 0;
		let Rez =
			Number(Rss1) +
			Number(Rss2) +
			Number(Rss3) +
			Number(Rss4) +
			Number(Rss5);
		for (let i = 0; i < 5; i++) {
			if (rezistente[i] != 0) j = j + 1;
		}
		let rezultat = Rez / j;

		console.log(rezultat);
		setRezultat(rezultat);
	}
	const [rezultat, setRezultat] =
		useState(0);

	function submitHandler2(event) {
		event.preventDefault();
		const Rpp1 = Rp1.current.value;
		const Rpp2 = Rp2.current.value;
		const Rpp3 = Rp3.current.value;
		const Rpp4 = Rp4.current.value;
		const Rpp5 = Rp5.current.value;
		const rezistente = [
			Rpp1,
			Rpp2,
			Rpp3,
			Rpp4,
			Rpp5,
		];
		let j = 0;
		let Rez = 0;
		for (let i = 0; i < 5; i++) {
			if (rezistente[i] != 0) 
		{	j = j + 1;
			Rez =
				Rez + Number(1 / rezistente[i]);
				console.log(Rez)}
		}
		let rezultat2 =  1/ j / Rez;
		rezultat2 =
			rezultat2.toPrecision(4);
		console.log(rezultat2);
		setRezultat2(rezultat2);
	}

	const [rezultat2, setRezultat2] =
		useState(0);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<Layout>
				<div class="flex">
					<div class="p-3 pt-5 w-1/2 ">
						<form
							class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
							onSubmit={submitHandler}
						>
							<h1 class="text-center text-3xl font-bold text-black-500 mb-10">
								Rezistenta serie
							</h1>
							<div class="mb-4">
								<label
									class="block text-gray-700 text-sm font-bold mb-2"
									for="password"
								>
									R1
								</label>
								<input
									ref={Rs1}
									class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
									id="Rs1"
									type="number"
									placeholder="R"
								/>
								<p class="text-red-500 text-xs italic">
									Minim 2 rezistente
								</p>
							</div>
							<div class="mb-4">
								<label
									class="block text-gray-700 text-sm font-bold mb-2"
									for="password"
								>
									R2
								</label>
								<input
									ref={Rs2}
									class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
									id="password"
									type="number"
									placeholder="R"
								/>
								<p class="text-red-500 text-xs italic">
									Minim 2 rezistente
								</p>
							</div>
							<div class="mb-4">
								<label
									class="block text-gray-700 text-sm font-bold mb-2"
									for="password"
								>
									R3
								</label>
								<input
									ref={Rs3}
									class="shadow appearance-none border border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
									id="password"
									type="number"
									placeholder="R"
								/>
							</div>
							<div class="mb-4">
								<label
									class="block text-gray-700 text-sm font-bold mb-2"
									for="password"
								>
									R4
								</label>
								<input
									ref={Rs4}
									class="shadow appearance-none border border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
									id="password"
									type="number"
									placeholder="R"
								/>
							</div>
							<div class="mb-4">
								<label
									class="block text-gray-700 text-sm font-bold mb-2"
									for="password"
								>
									R5
								</label>
								<input
									ref={Rs5}
									class="shadow appearance-none border border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
									id="password"
									type="number"
									placeholder="R"
								/>
							</div>
							<div class="flex items-center justify-between">
								<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
									Calculeaza
								</button>
							</div>
							<div class="mb-4">
								<h1 class="pt-4  text-xl font-bold text-black-500">
									Rezulat : {rezultat}
								</h1>
							</div>
						</form>
					</div>

					<div class="p-3 pt-5 w-1/2 ">
						<form
							onSubmit={submitHandler2}
							class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
						>
							<h1 class="text-center text-3xl font-bold text-black-500 mb-10">
								Rezistenta paralel
							</h1>
							<div class="mb-4">
								<label
									class="block text-gray-700 text-sm font-bold mb-2"
									for="password"
								>
									R1
								</label>
								<input
									ref={Rp1}
									class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
									id="Rs1"
									type="number"
									placeholder="R"
								/>
								<p class="text-red-500 text-xs italic">
									Minim 2 rezistente
								</p>
							</div>
							<div class="mb-4">
								<label
									class="block text-gray-700 text-sm font-bold mb-2"
									for="password"
								>
									R2
								</label>
								<input
									ref={Rp2}
									class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
									id="password"
									type="number"
									placeholder="R"
								/>
								<p class="text-red-500 text-xs italic">
									Minim 2 rezistente
								</p>
							</div>
							<div class="mb-4">
								<label
									class="block text-gray-700 text-sm font-bold mb-2"
									for="password"
								>
									R3
								</label>
								<input
									ref={Rp3}
									class="shadow appearance-none border border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
									id="password"
									type="number"
									placeholder="R"
								/>
							</div>
							<div class="mb-4">
								<label
									class="block text-gray-700 text-sm font-bold mb-2"
									for="password"
								>
									R4
								</label>
								<input
									ref={Rp4}
									class="shadow appearance-none border border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
									id="password"
									type="number"
									placeholder="R"
								/>
							</div>
							<div class="mb-4">
								<label
									class="block text-gray-700 text-sm font-bold mb-2"
									for="password"
								>
									R5
								</label>
								<input
									ref={Rp5}
									class="shadow appearance-none border border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
									id="password"
									type="number"
									placeholder="R"
								/>
							</div>
							<div class="flex items-center justify-between">
								<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
									Calculeaza
								</button>
							</div>
							<div class="mb-4">
								<h1 class="pt-4  text-xl font-bold text-black-500">
									Rezulat : {rezultat2}
								</h1>
							</div>
						</form>
					</div>
				</div>
			</Layout>
		</div>
	);
}
