import Head from "next/head";
import Layout from "../components/layout";
import { useState } from "react";

export default function Calculator() {
	function myFunction(event) {
		event.preventDefault();
		let rezultat=" -> Varianta Corecta"
		setRezultat(rezultat)
	}
	 const [rezultat, setRezultat] = useState("");
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<Layout>
				<form onSubmit={myFunction}>
					<div class="block p-5">
						<span class="  font-bold text-black-500  ">
							Releul termic se foloseşte
							pentru:
						</span>
						<div class="mt-2">
							<div>
								<label class="inline-flex items-center ">
									<input
										type="checkbox"
										class="form-checkbox text-green-500"
									/>
									<span class="ml-2 ">
										protejarea
										motoarelor electrice
										la scurtcircuit
									  	<span class="text-green-500">{rezultat}</span>
									</span>
								</label>
							</div>
							<div>
								<label class="inline-flex items-center">
									<input
										type="checkbox"
										class="form-checkbox text-red-500"
									/>
									<span class="ml-2">
										protejarea
										generatoarelor si
										motoarelor electrice
										împotriva punerii la
										pământ{" "}
									</span>
								</label>
							</div>
							<div>
								<label class="inline-flex items-center">
									<input
										type="checkbox"
										class="form-checkbox text-red-600"
									/>
									<span class="ml-2">
										{" "}
										protejarea
										motoarelor electrice
										la scurtcircuit
									</span>
								</label>
							</div>
						</div>
					</div>

					<div class="block p-5">
					<span class="  font-bold text-black-500 ">
							În cazul conexiunii în
							stea la transformator
						</span>
						<div class="mt-2">
							<div>
								<label class="inline-flex items-center ">
									<input
										type="checkbox"
										class="form-checkbox text-green-500"
									/>
									<span class="ml-2 ">
										tensiunea de linie
										este egală cu
										tensiunea de fază;<span class="text-green-500">{rezultat}</span>
									</span>
								</label>
							</div>
							<div>
								<label class="inline-flex items-center">
									<input
										type="checkbox"
										class="form-checkbox text-red-500"
									/>
									<span class="ml-2">
										curentul de linie
										este egal cu ~1,73 x
										curentul de fază;
									</span>
								</label>
							</div>
							<div>
								<label class="inline-flex items-center">
									<input
										type="checkbox"
										class="form-checkbox text-red-600"
									/>
									<span class="ml-2">
										tensiunea de linie
										este egală cu ~1,73
										x tensiunea de fază.
									</span>
								</label>
							</div>
						</div>
					</div>


					<div class="block p-5">
					<span class="  font-bold text-black-500 ">
							În cazul conexiunii în
							stea la transformator
						</span>
						<div class="mt-2">
							<div>
								<label class="inline-flex items-center ">
									<input
										type="checkbox"
										class="form-checkbox text-green-500"
									/>
									<span class="ml-2 ">
									16 mm2
									</span>
								</label>
							</div>
							<div>
								<label class="inline-flex items-center">
									<input
										type="checkbox"
										class="form-checkbox text-red-500"
									/>
									<span class="ml-2">
									25 mm2
									</span>
								</label>
							</div>
							<div>
								<label class="inline-flex items-center">
									<input
										type="checkbox"
										class="form-checkbox text-red-600"
									/>
									<span class="ml-2">
									10 mm2	<span class="text-green-500">{rezultat}</span>
									</span>
								</label>
							</div>
						</div>
					</div>



					<div class="block p-5">
					<span class="  font-bold text-black-500 ">
						Într-un circuit electric monofazat cu caracter inductiv tensiunea este defazata fata de curent:
						</span>
						<div class="mt-2">
							<div>
								<label class="inline-flex items-center ">
									<input
										type="checkbox"
										class="form-checkbox text-green-500"
									/>
									<span class="ml-2 ">
									cu zero grade (sunt în faza)
									</span>
								</label>
							</div>
							<div>
								<label class="inline-flex items-center">
									<input
										type="checkbox"
										class="form-checkbox text-red-500"
									/>
									<span class="ml-2">
									înainte cu 90 de grade	<span class="text-green-500">{rezultat}</span>
									</span>
								</label>
							</div>
							<div>
								<label class="inline-flex items-center">
									<input
										type="checkbox"
										class="form-checkbox text-red-600"
									/>
									<span class="ml-2">
									cu 90 de grade în urma
									</span>
								</label>
							</div>
						</div>
					</div>




					<div class="block p-5">
					<span class="  font-bold text-black-500 ">
							În cazul conexiunii în
							stea la transformator
						</span>
						<div class="mt-2">
							<div>
								<label class="inline-flex items-center ">
									<input
										type="checkbox"
										class="form-checkbox text-green-500"
									/>
									<span class="ml-2 ">
										tensiunea de linie
										este egală cu
										tensiunea de fază;<span class="text-green-500">{rezultat}</span>
									</span>
								</label>
							</div>
							<div>
								<label class="inline-flex items-center">
									<input
										type="checkbox"
										class="form-checkbox text-red-500"
									/>
									<span class="ml-2">
										curentul de linie
										este egal cu ~1,73 x
										curentul de fază;
									</span>
								</label>
							</div>
							<div>
								<label class="inline-flex items-center">
									<input
										type="checkbox"
										class="form-checkbox text-red-600"
									/>
									<span class="ml-2">
										tensiunea de linie
										este egală cu ~1,73
										x tensiunea de fază.
									</span>
								</label>
							</div>
						</div>
					</div>





					<div class="flex items-center justify-between py-1 px-5">
						<button
						
							class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
						>
							Verificare
						</button>
					</div>
				</form>
			</Layout>
		</div>
	);
}
