import Head from "next/head";
import Layout from "../components/layout";
import { useState } from "react";
import useSWR from "swr";


const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home(props) {
	const { data, error } = useSWR("/api/res", fetcher);

	if (error) return <div>failed to loadd</div>;
	if (!data) return <div></div>;

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
			<div class="flex items-center justify-center pt-4 w-100">
    <div class="flex border-2 border-gray-200 rounded ">
        <input type="text" class="px-4 py-2 w-60" placeholder="Ex: Ripan ( neimplementat )" />
        <button class="px-4 text-white bg-gray-600 border-l ">
            Cauta
        </button>
    </div>
</div>
				<div class="p-7 pt-5 grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
					{data.map((sd) => (
						<div class="max-w-sm bg-gray-50 rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
							<div class="p-5">
								<h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
								{sd.nume} {sd.prenume}
								</h5>

								<p class="mb-3 font-bold text-gray-900 dark:text-white">
								Poluton {sd.pluton} Companie {sd.companie} Batalion {sd.batalion}
								</p>
								<p class="mb-3 font-bold text-gray-900 dark:text-white">
								Nr.Telefon: {sd.telefon}
								</p>
								<p class="mb-3 font-bold text-gray-900 dark:text-white">
								Istoric: {sd.istoric}
								</p>
								<p class="mb-3 font-bold text-gray-900 dark:text-white">
								Puncte: {sd.puncte}
								</p>
								<a
									href="#"
									class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
								>
									Mai multe informatii
									<svg
										class="ml-2 -mr-1 w-4 h-4"
										fill="currentColor"
										viewBox="0 0 20 20"
										xmlns="http://www.w3.org/2000/svg"
									>
										<path
											fill-rule="evenodd"
											d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
											clip-rule="evenodd"
										></path>
									</svg>
								</a>
							</div>
						</div>
					))}
				</div>
			</Layout>
		</div>
	);
}


