import Head from "next/head";
import Layout from "../components/layout";

import useSWR from "swr";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
	const { data, error } = useSWR("/api/res", fetcher);

	if (error) return <div>failed to load</div>;
	if (!data) return <div></div>;

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div class="p-10 grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-5">
					{data.map((post) => (
						<div>
							<div class=" rounded overflow-hidden shadow-md">
								<img class="w-full" src={post.link} alt="Mountain"></img>
								<div class="px-6 py-4">
									<div class="font-bold text-xl mb-2">{post.title}</div>
									<p class="text-gray-700 text-base">{post.description}</p>
								</div>
								<div class="px-6 pt-4 pb-2">
									<span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
										Punctul A) {post.enteredH1}
									</span>
									<span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
										Punctul B) {post.enteredH2}
									</span>
									<span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
										Punctul C) {post.enteredH3}
									</span>
								</div>
							</div>
						</div>
					))}
				</div>
			</Layout>
		</div>
	);
}
